services:
  web:
    build: .
    command:  /usr/src/fullcost/create_cemes.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=full_coster
      - POSTGRES_PASSWORD=full_cost
      - POSTGRES_DB=full_cost_2

volumes:
  postgres_data: