# Generated by Django 5.1.4 on 2025-01-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_historicalgroup_options_and_more'),
        ('osm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical record', 'verbose_name_plural': 'historical records'},
        ),
        migrations.AlterField(
            model_name='experiment',
            name='exp_type',
            field=models.CharField(choices=[('SPECTRO', 'Optical Spectroscopy'), ('SPECTRO_CHEMISTRY', 'Optical Spectroscopy for Chemistry'), ('MAGNET', 'Magnetic Properties')], default='SPECTRO', max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='billing',
            field=models.CharField(choices=[('MET_C', 'Conventionnal TEM'), ('MET_A', 'Advanced TEM'), ('PREPA', 'Preparation for MET and MEB'), ('PREPA_SOFT', 'Soft Matter Preparation'), ('FIB_MEB', 'FIB Preparation and MEB'), ('SPECTRO', 'Optical Spectroscopy'), ('SPECTRO_CHEMISTRY', 'Optical Spectroscopy for Chemistry'), ('MAGNET', 'Magnetic Properties'), ('MATC', 'Material Caracterisation'), ('CLEANR', 'Clean Room Processes'), ('NEARF', 'Near-field microscopy'), ('FIB_LITHO', 'Lithography using the ZEISS'), ('CHEMISTRY', 'Chemistry'), ('GROWTH', 'Growth'), ('IMPLANT', 'Ionic Implantation'), ('UHVI', 'UHV Imagery'), ('DUFG', 'Growth DUF'), ('LT4P', 'LT-UHV 4 tips'), ('MECA', 'Mechanic Service'), ('ELEC', 'Electronic Service')], default='MET_C', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='extraction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='lab.extraction'),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='lab.group'),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='lab.project'),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='lab.user'),
        ),
        migrations.AlterField(
            model_name='record',
            name='billing',
            field=models.CharField(choices=[('MET_C', 'Conventionnal TEM'), ('MET_A', 'Advanced TEM'), ('PREPA', 'Preparation for MET and MEB'), ('PREPA_SOFT', 'Soft Matter Preparation'), ('FIB_MEB', 'FIB Preparation and MEB'), ('SPECTRO', 'Optical Spectroscopy'), ('SPECTRO_CHEMISTRY', 'Optical Spectroscopy for Chemistry'), ('MAGNET', 'Magnetic Properties'), ('MATC', 'Material Caracterisation'), ('CLEANR', 'Clean Room Processes'), ('NEARF', 'Near-field microscopy'), ('FIB_LITHO', 'Lithography using the ZEISS'), ('CHEMISTRY', 'Chemistry'), ('GROWTH', 'Growth'), ('IMPLANT', 'Ionic Implantation'), ('UHVI', 'UHV Imagery'), ('DUFG', 'Growth DUF'), ('LT4P', 'LT-UHV 4 tips'), ('MECA', 'Mechanic Service'), ('ELEC', 'Electronic Service')], default='MET_C', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='lab.extraction'),
        ),
        migrations.AlterField(
            model_name='record',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='lab.group'),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='lab.project'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='lab.user'),
        ),
    ]
