[activities]

[activities.MET]
name = 'Transmission Electron Microscopy Platform'
wu = 'day'
wu_label = 'Number of half day'
session_names = ['Morning', 'AfterNoon']
entities = [
    'MET_C',
    'MET_A',
]

[activities.PREPA]
name = 'Sample Preparation Service'
wu = 'sample'
wu_label = 'Number of samples'
session_names = ['Morning', 'AfterNoon', 'Evening']
entities = [
    'PREPA',
    'PREPA_SOFT',
]

[activities.FIB_MEB]
name = 'Focused Ion Beam and MEB'
wu = 'session'
wu_label = 'Number of sessions'
session_names = ['Morning', 'AfterNoon', 'Evening', 'Night']
night = false
entities = [
    'FIB_MEB',
]

[activities.OSM]
name = 'Optical Spectroscopy and Magnetism'
wu = 'day'
wu_label = 'Number of half day'
session_names = ['Morning', 'AfterNoon']
night = true
entities = [
    'SPECTRO',
    'SPECTRO_CHEMISTRY',
    'MAGNET'
]

[activities.CARAC]
name = 'Material Characterisation'
wu = 'day'
wu_label = 'Number of half day'
session_names = ['Morning', 'AfterNoon']
entities = [
    'MATC',
]

[activities.NANOFAB]
name = 'NanoFabrication'
wu = 'day'
wu_label = 'Number of half day'
session_names = ['Morning', 'AfterNoon']
night = true
entities = [
    'CLEANR',
    'NEARF',
    'FIB_LITHO',
]

[activities.CHEM]
name = 'Chemistry'
wu = 'day'
wu_label = 'Number of half day'
session_names = ['8h30-10h30', '10h30-12h30', '14h-16h', '16h-18h']
entities = [
    'CHEMISTRY',
]

[activities.GROWTH_IMP]
name = 'Growth and Implantation'
wu = 'duration'
wu_unit = 's'
wu_unity = 3600
wu_label = 'Number of hours'
entities = [
    'GROWTH',
    'IMPLANT',
]

[activities.STM_AFM]
name = 'UHV Imagery'
wu = 'day'
session_names = []
entities = [
    'DUFG',
    'UHVI',
    'LT4P',
]

[activities.ENGINEERING]
name = 'Engineering'
wu = 'day'
session_names = ['Morning', 'AfterNoon']
entities = [
    'MECA',
    'ELEC',
]