[activities]

[activities.MET]
name = 'Transmission Electron Microscopy Platform'
uo = 'day'
dates = 2
range_names = ['Morning', 'AfterNoon']
entities = [
    'MET_C',
    'MET_A',
]

[activities.PREPA]
name = 'Sample Preparation Service'
uo = 'sample'
dates = 1
range_names = ['Morning', 'AfterNoon', 'Evening']
entities = [
    'PREPA',
    'PREPA_SOFT',
]

[activities.FIB_MEB]
name = 'Focused Ion Beam and MEB'
uo = 'session'
dates = 1
range_names = ['Morning', 'AfterNoon', 'Evening', 'Night']
entities = [
    'FIB_MEB',
]

[activities.OSM]
name = 'Optical Spectroscopy and Magnetism'
uo = 'day'
dates = 2
range_names = ['Morning', 'AfterNoon', 'Night']
entities = [
    'SPECTRO',
    'SPECTRO_CHEMISTRY',
    'MAGNET'
]

[activities.CARAC]
name = 'Material Characterisation'
uo = 'day'
dates = 2
range_names = ['Morning', 'AfterNoon']
entities = [
    'MATC',
]

[activities.NANOFAB]
name = 'NanoFabrication'
uo = 'day'
dates = 2
range_names = ['Morning', 'AfterNoon', 'nights']
entities = [
    'CLEANR',
    'NEARF',
    'FIB_LITHO',
]

[activities.CHEM]
name = 'Chemistry'
uo = 'day'
dates = 2
range_names = ['8h30-10h30', '10h30-12h30', '14h-16h', '16h-18h']
entities = [
    'CHEMISTRY',
]

[activities.GROWTH_IMP]
name = 'Growth and Implantation'
uo = 'hours'
dates = 2
entities = [
    'GROWTH',
    'IMPLANT',
]

[activities.STM_AFM]
name = 'UHV Imagery'
uo = 'day'
dates = 2
range_names = ['Morning', 'AfterNoon']
entities = [
    'DUFG',
    'UHVI',
    'LT4P',
]

[activities.ENGINEERING]
name = 'Engineering'
uo = 'day'
dates = 2
range_names = ['Morning', 'AfterNoon']
entities = [
    'MECA',
    'ELEC',
]